[extension]
name = "pg_snowid"
version = "2.1.2"
repository = "https://github.com/qeeqez/snowid-postgres"
license = "PostgreSQL"
description = "Generate Snowflake-like IDs with speed and thread-safety in PostgreSQL"
homepage = "https://github.com/qeeqez/snowid-postgres"
documentation = "https://github.com/qeeqez/snowid-postgres"
categories = [
    "featured",
    "data_transformations"
]
loadable_libraries = [{ library_name = "pg_snowid", requires_restart = true }]

[build]
postgres_version = "18"
platform = "linux/arm64"
dockerfile = "Dockerfile"